apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
  namespace: kube-system
spec:
  selector:
    app: freeipa
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 80 
    targetPort: 80

