apiVersion: v1
kind: Pod
metadata:
  labels:
    name: freeipa
  name: freeipa
  annotations:
    cni.projectcalico.org/ipAddrs: "[\"10.2.110.20\",\"fd20::8b78\"]"
  namespace: kube-system
spec:
  hostname: freeipa1
  subdomain: default-subdomain
  containers:
  - name: freeipa-server
    env:
      - name: HOSTNAME
        value: freeipa1.default-subdomain.kube-system.svc.k8s.cluster
    image: 117.25.155.104:5000/port/freeipa-service:latest 
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
      privileged: true
    volumeMounts:
      - mountPath: /etc/harbor
        name: harbor-config
      - mountPath: /data/ipa-server-install-options
        name: ipa-server-install-options
        subPath: ipa-server-install-options
      - mountPath: /data3
        name: freeipadata
      - mountPath: /sys/fs/cgroup
        name: sysfscgroup
      - mountPath: /tmp
        name: tmp
      - mountPath: /var/log
        name: log
  volumes:
    - name: harbor-config
      hostPath:
        path: /etc/harbor
    - name: sysfscgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: tmp
      hostPath:
        path: /tmp
    - name: run
      hostPath:
        path: /run
    - name: log
      hostPath:
        path: /var/log
    - name: freeipadata
      hostPath:
        path: /var/lib/freeipa/
    - name: ipa-server-install-options
      configMap:
        name: ipa-server-install-options
        items:
        - key: ipa-server-install-options
          path: ipa-server-install-options
        
