apiVersion: v1
kind: Service
metadata:
  name: freeipa
  namespace: kube-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: freeipa
  clusterIP: 10.3.0.11
  sessionAffinity: None
  type: ClusterIP
