apiVersion: v1
data:
  apiserver.crt: ${apiserver_cert}
  apiserver.key: ${apiserver_key}
  ca.crt: ${ca_cert}
  etcd-client-ca.crt: ${etcd_ca_cert}
  etcd-client.crt: ${etcd_client_cert}
  etcd-client.key: ${etcd_client_key}
  service-account.pub: ${serviceaccount_pub}
kind: Secret
metadata:
  name: kube-apiserver
  namespace: ${kube_system}
type: Opaque
