apiVersion: v1
data:
  ca.crt: ${ca_cert}
  ca.key: ${etcd_client_cert}
  service-account.key: ${etcd_client_key}
kind: Secret
metadata:
  name: kube-controller-manager
  namespace: ${kube_system}
type: Opaque
