apiVersion: v1
data:
  ca.crt: ${ca_cert}
  ca.key: ${ca_key}
  service-account.key: ${serviceaccount_key}
kind: Secret
metadata:
  name: kube-controller-manager
  namespace: ${kube_system}
type: Opaque
